{
 "title": "环境监测面板",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "湿度",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  hum,\n  \"湿度\" AS metric\nFROM humTB\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "信号强度",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  CSQ,\n  \"信号\" AS metric\nFROM csqTB\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "温度",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temp\nFROM tempTB\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "地图",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 19, "w": 10, "x": 7, "y": 3 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temp_value AS \"metric\",\n  ele AS \"ele\",\n  lat AS \"latitude\",\n  lng AS \"longitude\"\nFROM GPS\nWHERE\n  $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "湿度表",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \nid as \"id\",\nhum as \"湿度\",\nimei as \"设备\",\ntime as \"时间\"\nfrom humTB"
    }
   ]
  },
  {
   "title": "温度表",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \nid as \"id\",\ntemp as \"温度\",\nimei as \"设备\",\ntime as \"时间\"\nfrom tempTB"
    }
   ]
  },
  {
   "title": "湿度曲线图",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  hum,\n  \"湿度\" AS metric\nFROM humTB\nWHERE\n  $__timeFilter(time)\nORDER BY $__timeGroup(time,$__interval) "
    }
   ]
  },
  {
   "title": "温度曲线图",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  temp,\n  \"温度\" AS metric\nFROM tempTB\nWHERE\n  $__timeFilter(time)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "GPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT id as 'id',\nlng as '经度',\nlat as '纬度',\ntemp_value as '实时温度',\nele as '海拔高度',\ntime as '时间'\nfrom GPS"
    }
   ]
  }
 ]
}